packages:
    - .

overrides:
    flatted: '>=3.4.2'
    'picomatch@>=4.0.0 <4.0.4': '>=4.0.4'
    serialize-javascript: '>=7.0.3'
    'brace-expansion@>=4.0.0 <5.0.11': '^5.0.11'
    'fast-uri@>=3.0.0 <3.1.8': '^3.1.8'
    'shell-quote@>=1.8.4 <1.11.0': '^1.11.0'
    'source-map-js@<1.2.2': '^1.2.2'
