import Order from './resources/order';
import Payload from './resources/payload';
import Entity from './resources/entity';
import Place from './resources/place';
import Waypoint from './resources/waypoint';
import TrackingStatus from './resources/tracking-status';
import Vehicle from './resources/vehicle';
import Organization from './resources/organization';
import Driver from './resources/driver';
import Vendor from './resources/vendor';
import Contact from './resources/contact';
import Zone from './resources/zone';
import ServiceArea from './resources/service-area';
import ServiceRate from './resources/service-rate';
import ServiceQuote from './resources/service-quote';
export { Order, Payload, Entity, Place, Waypoint, TrackingStatus, Vehicle, Organization, Driver, Vendor, Contact, Zone, ServiceArea, ServiceRate, ServiceQuote };
